### ISSUE TITLE
typos "registrationEmailAsUsername.tooltip"

### ISSUE THREAD

**Issue by tnorimat** [k-tamura/keycloak-japanese-properties#4]
https://github.com/k-tamura/keycloak400-japanese-properties/blob/4fe17b003ff7249ef83a5fdc44260f9782eb3dfb/themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties#L33

registrationEmailAsUsername.tooltip=有効の場合は、登録フォームにおいてユーザー名フィールドが非表示なり、Eメールが新規ユーザーのユーザー名として使われます。

を

registrationEmailAsUsername.tooltip=有効の場合は、登録フォームにおいてユーザー名フィールドが非表示となり、Eメールが新規ユーザーのユーザー名として使われます。

としたらいかがでしょうか。

**Comment by k-tamura** [comment]
あ、「と」が抜けてましたね...修正します。
