### ISSUE TITLE
typos "resetPasswordAllowed.tooltip"

### ISSUE THREAD

**Issue by tnorimat** [k-tamura/keycloak-japanese-properties#5]
https://github.com/k-tamura/keycloak400-japanese-properties/blob/4fe17b003ff7249ef83a5fdc44260f9782eb3dfb/themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties#L37

resetPasswordAllowed.tooltip=クレデンシャルを忘れてしまった場合にクリックするリンクをログインページに表示します。

を

resetPasswordAllowed.tooltip=パスワードを忘れてしまった場合にクリックするリンクをログインページに表示します。

としたらいかがでしょうか。パスワードの方がわかりやすいのではと思いました。

**Comment by k-tamura** [comment]
そうですね。この機能はパスワードに限定されているので、「クレデンシャル」という抽象的な表現より、具体的な「パスワード」の方が分かりやすいですね。修正します。
