### ISSUE TITLE
typos "docker-auth.tooptip"

### ISSUE THREAD

**Issue by tnorimat** [k-tamura/keycloak-japanese-properties#6]
https://github.com/k-tamura/keycloak400-japanese-properties/blob/4fe17b003ff7249ef83a5fdc44260f9782eb3dfb/themes/src/main/resources-community/theme/base/admin/messages/admin-messages_ja.properties#L963

docker-auth.tooptip=ドッカークライアントに対する認証に使用するフローを選択します。

を

docker-auth.tooptip=Dockerクライアントに対する認証に使用するフローを選択します。

としたらいかがでしょうか。ドッカー というのがちょっと違和感があったためです。

**Comment by k-tamura** [comment]
Dockerですね（訳しておいてなんですが、私も「ドッカー」には違和感があります）。修正します。
